# Generated by Django 5.2.12 on 2026-03-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='ngo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
