# Generated by Django 5.2.12 on 2026-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ngo_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='organization_name',
            new_name='org_name',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='status',
        ),
        migrations.AddField(
            model_name='ngo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='certificate',
            field=models.ImageField(upload_to='ngo_certificates/'),
        ),
    ]
