# Generated by Django 5.2.12 on 2026-03-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_food_claimed_by_food_is_claimed_grocery_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
